Prefix: ''
cmd:
 tp:
  names:
   - tp
  permission: 'yuanlu.serverDo.tp'
  description: 'tp cmd'
  usageMessage: '/tp <target>'
 tpa:
  names:
   - tpa
  permission: 'yuanlu.serverDo.tpa'
  description: 'tpa cmd'
  usageMessage: '/tpa <target>'
 tphere:
  names:
   - tphere
  permission: 'yuanlu.serverDo.tphere'
  description: 'tphere cmd'
  usageMessage: '/tphere <target>'
 tpahere:
  names:
   - tpahere
  permission: 'yuanlu.serverDo.tpahere'
  description: 'tpahere cmd'
  usageMessage: '/tpahere <target>'
 tpaccept:
  names:
   - tpaccept
  permission: 'yuanlu.serverDo.tpaccept'
  description: 'tpaccept cmd'
  usageMessage: '/tpaccept <target>'
 tpdeny:
  names:
   - tpdeny
  permission: 'yuanlu.serverDo.tpdeny'
  description: 'tpdenycmd'
  usageMessage: '/tpdeny <target>'
message:
  LanguageFileIsLost: '&c&l[语言文件缺失]节点:%node%'
  not-player: "&c您不是玩家!"
  no-permission: "&c您没有权限"
  cmd:
    help: '模板内容'
    tp:
      receiver: ""
      third-mover: ""
      third-target: ""
      tp: "&7正在传送至 &2%2$s"
      tp-third: "&7正在将 &2%2$s &7传送至 &2%4$s"
      help: "&7输入指令： &2/tp <玩家> &7传送到某玩家的位置"
      not-found: "&7未找到玩家 &2%s"
    tpa:
      receiver: 
        #一个高级语言节点, 接受json文本
        json: '["",{"text":"&2%s &7请求传送到您这里\n"},{"text":"&7若想接受传送，输入 &2/tpaccept\n","clickEvent":{"action":"run_command","value":"/tpaccept"},"hoverEvent":{"action":"show_text","value":["",{"text":"点击运行","bold":true}]}},{"text":"&7若想拒绝传送，输入 &2/tpdeny\n","clickEvent":{"action":"run_command","value":"/tpdeny"},"hoverEvent":{"action":"show_text","value":["",{"text":"点击运行","bold":true}]}},{"text":"&7此传送请求将在 &2%s &7秒后自动超时"}]'
        msg:
          #备用信息, 对于一些不支持json的版本/模块显示的信息
          - "&2%s &7请求传送到您这里"
          - "&7若想接受传送，输入 &2/tpaccept"
          - "&7若想拒绝传送，输入 &2/tpdeny"
          - "&7此传送请求将在 &2%s &7秒后自动超时"
      send: 
        #一个高级语言节点, 接受json文本
        json: '["",{"text":"&7请求已发送给 &2%2$s\n"},{"text":"&7想要取消这个传送请求，请输入 &2/tpacancel","clickEvent":{"action":"run_command","value":"/tpacancel"},"hoverEvent":{"action":"show_text","value":["",{"text":"点击运行","bold":true}]}}]'
        msg:
          #备用信息, 对于一些不支持json的版本/模块显示的信息
          - "请求已发送给 &2%2$s"
          - "&7想要取消这个传送请求，请输入 &2/tpacancel"
      accept: message.cmd.tpa.accept
      deny: message.cmd.tpa.deny
      self-tp: message.cmd.tpa.self-tp
      help: "&7输入指令： &2/tpa <玩家> &7请求传到送某玩家的位置"
    tphere:
      receiver: message.cmd.tphere.receiver
      success: message.cmd.tphere.success
      help: "&7输入指令： &2/tphere <玩家> &7传送某玩家到您的位置"
    tpahere:
      receiver: message.cmd.tpahere.receiver
      send: message.cmd.tpahere.send
      accept: message.cmd.tpahere.accept
      deny: message.cmd.tpahere.deny
      help: "&7输入指令： &2/tpahere <玩家> &7请求某玩家传送到您的位置"
    tpaccept:
      success: message.cmd.tpaccept.success
      no-request: message.cmd.tpaccept.no-request
      not-found: message.cmd.tpaccept.not-found
      timeout: message.cmd.tpaccept.timeout
    tpdeny:
      success: message.cmd.tpdeny.success
      no-request: message.cmd.tpdeny.no-request
      not-found: message.cmd.tpdeny.not-found
      timeout: message.cmd.tpdeny.timeout
  basic:
    message-time-out: message.basic.message-time-out
    version-bad: message.basic.version-bad
    bungee-error: message.basic.bungee-error
    bungee-player-offline: message.basic.bungee-player-offline
