Prefix: ''
setting:
  permission:
    no-delay: 'yuanlu.serverDo.no-delay' #无延时
    no-cooldown: 'yuanlu.serverDo.no-cooldown' #无冷却
    tp-senior: "yuanlu.serverDo.tpSenior" #高级传送, 包括传送隐身玩家, 跨组传送
    tp-other: "yuanlu.serverDo.tpOther" #第三方传送
    home:
      'default': 3
      '10': "yuanlu.serverDo.home.10"
      '50':
       - "yuanlu.serverDo.home.50"
       - "yuanlu.serverDo.home.another-permission-50"
  teleport-delay: 3
  teleport-cooldown: 100
  request-overtime: 120
  use-safeLocation: false
#所有的命令, 删除某个节点将关闭对应的命令
cmd:
 reload:
  names: 'ysd-reload'
 tp:
  names:
   - tp
  permission: 'yuanlu.serverDo.tp'
  description: 'tp cmd'
  usageMessage: '/tp <target>'
  def-cmd: 'minecraft:tp'
 tpa:
  names:
   - tpa
  permission: 'yuanlu.serverDo.tpa'
  description: 'tpa cmd'
  usageMessage: '/tpa <target>'
 tphere:
  names:
   - tphere
  permission: 'yuanlu.serverDo.tphere'
  description: 'tphere cmd'
  usageMessage: '/tphere <target>'
 tpahere:
  names:
   - tpahere
  permission: 'yuanlu.serverDo.tpahere'
  description: 'tpahere cmd'
  usageMessage: '/tpahere <target>'
 tpaccept:
  names:
   - tpaccept
  permission: 'yuanlu.serverDo.tpaccept'
  description: 'tpaccept cmd'
  usageMessage: '/tpaccept [target]'
 tpdeny:
  names:
   - tpdeny
  permission: 'yuanlu.serverDo.tpdeny'
  description: 'tpdeny cmd'
  usageMessage: '/tpdeny [target]'
 tpcancel:
  names:
   - tpcancel
  permission: 'yuanlu.serverDo.tpcancel'
  description: 'tpcancel cmd'
  usageMessage: '/tpcancel [target]'
 vanish:
  names:
   - 'ysd-v'
  permission: 'yuanlu.serverDo.vanish'
  description: 'vanish cmd'
  usageMessage: '/ysd-v [always]'
 warp:
  names:
   - 'warp'
  permission: 'yuanlu.serverDo.warp'
  description: 'warp cmd'
  usageMessage: '/warp [name]'
 set-warp:
  names:
   - 'setwarp'
  permission: 'yuanlu.serverDo.set-warp'
  description: 'set-warp cmd'
  usageMessage: '/setwarp <name>'
 del-warp:
  names:
   - 'delwarp'
  permission: 'yuanlu.serverDo.del-warp'
  description: 'del-warp cmd'
  usageMessage: '/delwarp <name>'
 home:
  names:
   - 'home'
  permission: 'yuanlu.serverDo.home'
  description: 'home cmd'
  usageMessage: '/home [name]'
 set-home:
  names:
   - 'sethome'
  permission: 'yuanlu.serverDo.set-home'
  description: 'set-home cmd'
  usageMessage: '/sethome [name]'
 del-home:
  names:
   - 'delhome'
  permission: 'yuanlu.serverDo.del-home'
  description: 'del-home cmd'
  usageMessage: '/delhome <name>'
 trans:
  names:
   - 'ysd-trans'
  permission: 'yuanlu.serverDo.ysd-trans'
  description: 'ysd-trans cmd'
  usageMessage: '/ysd-trans <plugin> <func>'
message:
  LanguageFileIsLost: '&c&l[语言文件缺失]节点:%node%'
  not-player: '&c您不是玩家!'
  no-permission: '&c您没有权限: &7%s'
  version-no-recommend: '&c服务器版本不一致: %s <-> %s'
  cmd:
    help: '&7yuanluServerDo'
    tp:
      receiver: ''
      third-mover: ''
      third-target: ''
      sender: '&7正在传送至 &2%2$s'
      third-tp: '&7正在将 &2%2$s &7传送至 &2%4$s'
      help:
        - '&7输入指令： &2/tp <玩家> &7传送到某玩家的位置'
        - '&7输入指令： &2/tp <玩家1> <玩家2> &7将&2玩家1&7传送到&2玩家2&7的位置'
      not-found: '&7未找到玩家 &2%s'
    tpa:
      receiver:
        json: '["",{"text":"&2%2$s &7请求传送到您这里\n"},{"text":"&7若想接受传送，输入 &2/tpaccept\n","clickEvent":{"action":"run_command","value":"/tpaccept %1$s"},"hoverEvent":{"action":"show_text","value":["",{"text":"接受传送","bold":true}]}},{"text":"&7若想拒绝传送，输入 &2/tpdeny\n","clickEvent":{"action":"run_command","value":"/tpdeny %1$s"},"hoverEvent":{"action":"show_text","value":["",{"text":"拒绝传送","bold":true}]}},{"text":"&7此传送请求将在 &2%3$s &7秒后自动超时"}]'
        msg:
        - '&2%2$s &7请求传送到您这里'
        - '&7若想接受传送，输入 &2/tpaccept'
        - '&7若想拒绝传送，输入 &2/tpdeny'
        - '&7此传送请求将在 &2%3$s &7秒后自动超时'
      sender:
        json: '["",{"text":"&7请求已发送给 &2%2$s\n"},{"text":"&7想要取消这个传送请求，请输入 &2/tpacancel","clickEvent":{"action":"run_command","value":"/tpcancel %1$s"},"hoverEvent":{"action":"show_text","value":["",{"text":"取消传送","bold":true}]}}]'
        msg:
        - 请求已发送给 &2%2$s
        - '&7想要取消这个传送请求，请输入 &2/tpacancel'
      accept-wait: "&2%2$s &7接受了您的传送请求, 将在 &2%3$s &7秒后启动"
      accept: "&7正在传送至 &2%2$s"
      deny: "&2%2$s &7拒绝了您的传送请求"
      self-tp: "&7您不能向自己发送传送请求"
      help: '&7输入指令： &2/tpa <玩家> &7请求传到送某玩家的位置'
      cooldown: "&7您还需要等待 &2%.3f &7秒"
      not-found: '&7未找到玩家 &2%s&7, 或所在服务器无法传送'
    tphere:
      receiver: ''
      sender: "&7正在将 &2%2$s &7传送到您的位置"
      help: '&7输入指令： &2/tphere <玩家> &7传送某玩家到您的位置'
      not-found: '&7未找到玩家 &2%s'
    tpahere:
      sender:
        json: '["",{"text":"&7请求已发送给 &2%2$s\n"},{"text":"&7想要取消这个传送请求，请输入 &2/tpacancel","clickEvent":{"action":"run_command","value":"/tpcancel %1$s"},"hoverEvent":{"action":"show_text","value":["",{"text":"点击运行","bold":true}]}}]'
        msg:
          #备用信息, 对于一些不支持json的版本/模块显示的信息
          - "请求已发送给 &2%2$s"
          - "&7想要取消这个传送请求，请输入 &2/tpacancel"
      receiver:
        json: '["",{"text":"&2%2$s &7请求传送您到他那里n"},{"text":"&7若想接受传送，输入 &2/tpaccept\n","clickEvent":{"action":"run_command","value":"/tpaccept %1$s"},"hoverEvent":{"action":"show_text","value":["",{"text":"接受传送","bold":true}]}},{"text":"&7若想拒绝传送，输入 &2/tpdeny\n","clickEvent":{"action":"run_command","value":"/tpdeny %1$s"},"hoverEvent":{"action":"show_text","value":["",{"text":"拒绝传送","bold":true}]}},{"text":"&7此传送请求将在 &2%3$s &7秒后自动超时"}]'
        msg:
          - "&2%2$s &7请求传送您到他那里"
          - "&7若想接受传送，输入 &2/tpaccept"
          - "&7若想拒绝传送，输入 &2/tpdeny"
          - "&7此传送请求将在 &2%3$s &7秒后自动超时"
      accept: "&2%2$s &7已接受请求"
      deny: "&2%2$s &7拒绝了您的传送请求"
      help: '&7输入指令： &2/tpahere <玩家> &7请求某玩家传送到您的位置'
      self-tp: "&7您不能向自己发送传送请求"
      cooldown: "&7您还需要等待 &2%.3f &7秒"
      not-found: '&7未找到玩家 &2%s&7, 或所在服务器无法传送'
    tpaccept:
      success: "&7已接受 &2%2$s &7的请求"
      success-wait: "&7您接受了 &2%2$s &7的传送请求, 将在 &2%3$s &7秒后启动"
      no-request: "&7您没有要接受的请求"
      not-found: "&7找不到 &2%s &7的请求"
      timeout: "&7最后一个请求已超时 &2%.3f &7秒"
    tpdeny:
      success: "&7您拒绝了 &2%2$s &7的传送请求"
      no-request: "&7您没有要接受的请求"
      not-found: "&7找不到 &2%s &7的请求"
      timeout: "&7最后一个请求已超时 &2%.3f &7秒"
    tpcancel:
      remote-fail: "&c由于未知原因, &2%s &c试图取消一个不存在的请求"
      remote-success: "&2%2$s &7取消了传送"
      success: "&7你取消了发送给 &2%2$s &7的传送请求"
    vanish:
      always-hide: '&7已 &2开启 &7自动隐藏您的身份'
      always-show: '&7已 &2关闭 &7自动隐藏您的身份'
      auto-hide: '&7已自动隐藏您的身份'
      hide: '&7已在列表中 &2隐藏 &7您的身份'
      show: '&7已在列表中 &2显示 &7您的身份'
      help:
       - '&7输入指令： &2/ysd-v &7切换YSD隐身状态'
       - '&7输入指令： &2/ysd-v always &7切换YSD自动隐身状态'
    reload:
      success: '&c成功重载(此功能为实验性功能, 若出现任何错误请使用服务器重载指令或重启服务器)'
      only-console: '&7请在控制台使用此指令'
    warp:
      list:
        - '%s'
        - '%s'
      list-w1: '&7同组地标(&2%2$s&7): %1$s&7'
      list-w2: '&7跨组地标(&2%2$s&7): %1$s&7'
      list-element: '&2%2$s'
      list-delimiter: '&7, ' 
      tp: '&7正在传送至地标 &2%s&7(&2%s&7)'
      not-found: '&7找不到地标 &2%s'
    del-warp:
      success: '&7成功删除地标 &2%s'
      fail: '&7找不到地标 &2%s'
      help: '&7输入指令： &2/delwarp <name> &7删除地标'
    set-warp:
      success: '&7成功设置地标 &2%s'
      help: '&7输入指令： &2/setwarp <name> &7设置地标'
    home:
      list:
        - '%s'
        - '%s'
      list-w1: '&7同组家(&2%2$s&7): %1$s&7'
      list-w2: '&7跨组家(&2%2$s&7): %1$s&7'
      list-element: '&2%2$s'
      list-delimiter: '&7, ' 
      tp: '&7正在传送至家 &2%s&7(&2%s&7)'
      not-found: '&7找不到家 &2%s'
    del-home:
      success: '&7成功删除家 &2%s'
      fail: '&7找不到家 &2%s'
      help: '&7输入指令： &2/delhome <name> &7删除家'
    set-home:
      success: '&7成功设置家 &2%s'
      fail: '&7家数量已达上限: &2%s'
    trans:
      help: '&7输入指令：&2/ysd-trans <plugin> <func> &7从某插件转换数据'
      not-found: '&7找不到名为 &2&s &7的转换器'
      invlid: '&7转换器 &2%s &7不可用'
      cannot: '&7转换器 &2%s &7不可以完成 &2&s &7的功能'
      title: '&7转换器 &2%s &7运行中'
      sub-title: '&7进度: &6%s&7/&2%s&r'
      success: '&7已完成转换: 完成 &2%s &7(预计 &2%s &7)'
      help-CMI:
        - '&2CMI &7转换器可用功能: '
        - '&7 - &2all-home &7转换全部的家数据'
  basic:
    message-time-out: "&c服务器通讯超时, 请联系管理员"
    version-bad: "&c服务器版本检查失败, 请联系管理员"
    bungee-error: "&cBC服务器发生错误, 请联系管理员"
    bungee-player-offline: "&7对方已离线"
  tpcancel-move: "&7由于移动，传送任务被取消"