#跨服传送组
server-group:
  #同一组内可以使用/tpa, /tpahere等命令
  group1:
    - server1
    - server2
  group2:
    - server3
    - server4
#禁用的服务器, 例如登录服务器
server-ban:
  - 'auth'
  - 'lobby'

#名称获取设置
setting:
  #如果设置为true，在允许的情况下，从子服获取玩家名称，否则全由bungeecord获取玩家名称
  sub-server-display-name: false

#玩家tab替换内容，可任意修改
player-tab-replace: "%%%yuanlu-tab-player-list"

#时间校准循环间隔(ms)
timeAmend: 300000

#自动保存延时(ms)
save-delay: 60000

#是否启用at
use-at: true
